# Site settings
name: Joyce de Souza
description: "Minha primeira pagina pessoal pelo github"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  JoyceSforzin
facebook_username: joyce.sforzin
google_plus_username: your_google_plus_username_goes_here
instagram_username:  joyce_sforzin
email: joyce_sforzin@hotmail.com
public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars3.githubusercontent.com/u/53825558?s=400&u=3a6594efc8bca72d7ecfee20c4c7bd8dc6136bbe&v=4"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
